#!/usr/bin/env bash                                                                                                                                       
# fix nginx listening port 80                                                                                                                          
# Go to sites-enabled folder for Nginx                                                                                                                    
cd /etc/nginx/sites-enabled/ || exit;                                                                                                                             
# Delete the default file                                                                                                                               
rm default;                                                                                                                                               
# Create symbolic link to the deafult file sites-available                                                                                             
ln -s /etc/nginx/sites-available/default default;                                                                                                         
# Restart Nginx                                                                                                                                           
service nginx restart 