#!/usr/bin/env bash
# FizzBuzz!!

for j in $(seq 1 100);
do
    if [ $((j % 15)) -eq 0 ]; then
	echo "FizzBuzz"
    elif [ $((j % 3)) -eq 0 ]; then
	echo "Fizz"
    elif [ $((j % 5)) -eq 0 ]; then
	echo "Buzz"
    else
	echo "$j"
    fi
done
