#!/usr/bin/env bash
#  display the content of the file /etc/passwd
#+ only displays the:
#+ username
#+ group id
#+ Shell full path for the user

while IFS= read -r LI; do
    echo "$LI" | cut -d':' -f1,4,7
done < /etc/passwd
