#!/usr/bin/env bash
# Parses Apache log file in list format.
#   Groups visitors by IP and HTTP status code
#   Display the number of occurrence, IP, and HTTP status

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
