#!/usr/bin/env bash
# Displays "Best School" 10 time using a while loop.
#   On the 9 iteration, displays "Hi" before "Best School".

counter=0

while [ $counter -lt 10 ]
do
  if [ $counter -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( counter++ ))
done
