#!/usr/bin/env bash
# prints a string 10 times using while loop

v=1

while [ "$v" -lt 11 ]; do
  echo "Best School"
  
  # if statement to print Hi when v is 9
  if [ "$v" -eq 9 ]; then
    echo "Hi"
  fi

  ((v++))
done
