#!/usr/bin/env bash
# Display "Best School" 10 time
# display "Best School" and then "Hi"
v=1
while [ $v -le 10 ]
do
	if [ $v = 10 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	v=$(( v + 1 ))
done
