#!/usr/bin/env bash
# display the numbers 1 to 20 and display
#+ "bad luck from China" after the 4 loop
#+ "bad luck from Japan" after the 9 loop
#+ "bad luck from Italy" after the 17 loop

COUNT=1
while [ "$COUNT" -le 20 ]; do
    echo "$COUNT"
    case "$COUNT" in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    let COUNT=COUNT+1
done
