#!/usr/bin/env bash
# display the time for 12 hour and 59 minute

H=0
while [ "$H" -lt 13 ]; do
    echo "H: $H"
    M=1
    while [ "$M" -lt 60 ]; do
	echo "$M"
	let M=M+1
    done
    let H=H+1
done
